org: aaronm37
console: true
service: riot-stats
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2

functions:
  getMatches:
    handler: getMatches.getMatches
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
